manifest: undo updates to node-sources.json and yarn.lock
After commit 2e6f4456 ("manifest: update lrcget to 1.0.0"), running the
'tauri bundle' command begin failing with:

===
$ tauri build --no-bundle
        Info Looking up installed tauri packages to check mismatched versions...
Found version mismatched Tauri packages. Make sure the NPM and crate versions are on the same major/minor releases:
tauri (v2.1.1) : @tauri-apps/api (v2.8.0)
tauri-plugin-dialog (v2.2.0) : @tauri-apps/plugin-dialog (v2.4.0)
tauri-plugin-shell (v2.2.0) : @tauri-apps/plugin-shell (v2.3.1)
tauri-plugin-os (v2.2.0) : @tauri-apps/plugin-os (v2.3.1)
tauri-plugin-global-shortcut (v2.2.0) : @tauri-apps/plugin-global-shortcut (v2.3.0)
       Error Found version mismatched Tauri packages. Make sure the NPM and crate versions are on the same major/minor releases:
tauri (v2.1.1) : @tauri-apps/api (v2.8.0)
tauri-plugin-dialog (v2.2.0) : @tauri-apps/plugin-dialog (v2.4.0)
tauri-plugin-shell (v2.2.0) : @tauri-apps/plugin-shell (v2.3.1)
tauri-plugin-os (v2.2.0) : @tauri-apps/plugin-os (v2.3.1)
tauri-plugin-global-shortcut (v2.2.0) : @tauri-apps/plugin-global-shortcut (v2.3.0)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: module lrcget: Child process exited with code 1
===

I haven't looked into this properly, but from a quick search it seems
like tauri-cli >= 2.8.0 now requires the npm and cargo versions to match.